<?php
// Strings for Exception messages.
$strings = array();

// Strings for File System
$strings['EXCEPTION_FILE_SYSTEM_NOT_FOUND'] = 'File system !uri not found.';

// Strings for Factory
$strings['EXCEPTION_FACTORY_NOT_FOUND'] = 'Factory !name not found.';

// Strings for Update Instance
$strings['EXCEPTION_UPDATE_INSTANCE_NOT_FOUND'] = 'Update instance !name not found.';
$strings['EXCEPTION_UPDATE_FOLDER_NOT_FOUND'] = '!name Update requires folder !folder.';
$strings['EXCEPTION_UPDATE_MODULE_NOT_FOUND'] = '!name Update requires module !module.';
$strings['EXCEPTION_UPDATE_CONTENT_EMPTY'] = '!name Update file !file content is empty.';
$strings['EXCEPTION_UPDATE_INVALID_EXTENSION'] = '!name Update file !file extension invalid.';
$strings['EXCEPTION_UPDATE_COMPRESSION_NOT_SUPPORT'] = '!name Update compressed file !file not supported.';
$strings['EXCEPTION_UPDATE_FOLDER_NO_FILE'] = '!name Update folder !folder has no file.';

// Strings for Struct
$strings['EXCEPTION_ENTITY_STRUCT_NOT_FOUND'] = 'Entity struct !name not found.';
$strings['EXCEPTION_ENTITY_INFO_NOT_FOUND'] = 'Entity infomation for type !type not found.';
$strings['EXCEPTION_ENTITY_FIELD_NOT_FOUND'] = 'Fields in entity !classType !entity not found.';
$strings['EXCEPTION_HOOK_CLASS_TEMPLATE_NOT_FOUND'] = 'Hook class template !name not found.';
$strings['EXCEPTION_PROJECT_FOLDER_NOT_FOUND'] = 'The root folder !folder for project specific module not created.';
$strings['EXCEPTION_PROJECT_FOLDER_CREATION_FAILURE'] = 'The folder !folder is not created.';
$strings['EXCEPTION_PROJECT_MODULE_NOT_SET'] = 'The project module is not specified.';
$strings['EXCEPTION_PROJECT_CLASS_PREFIX_NOT_SET'] = 'The project class prefix is not specified.';

// Strings for String
$strings['EXCEPTION_STRING_NOT_FOUND'] = 'Stirng !id not found.';
$strings['EXCEPTION_STRING_FILE_NOT_FOUND'] = 'String file !file not found.';

// Strings for Entity class
$strings['EXCEPTION_ENTITY_FUNC_PARAM_TYPE_NOT_MATCH'] = 'Entity function !func requires !type for !param.';
$strings['EXCEPTION_ENTITY_LOAD_NO_RESULT'] = 'Entity loads no result with conditions: !conditions.';

$strings['EXCEPTION_ENTITY_OP_NOT_FOUND'] = 'Entity !type Op !name not found.';